CREATE OR REPLACE PROCEDURE QGPL.GET_ENVVAR (
  IN  IN_ENVVAR         VARCHAR(128) ,
  OUT OUT_VALUE         VARCHAR(1024)
)

LANGUAGE SQL
MODIFIES SQL DATA

BEGIN

    SELECT
      ENVIRONMENT_VARIABLE_VALUE
    INTO
      OUT_VALUE
    FROM
      QSYS2.ENVIRONMENT_VARIABLE_INFO
    WHERE
      ENVIRONMENT_VARIABLE_NAME = IN_ENVVAR
    FETCH FIRST 1 ROWS ONLY ;

END ;